import { BrainCircuit, CircleHelp, Cpu, Gauge, Sparkles, Terminal, Zap } from "lucide-react";
import type { Stage, StageId } from "./types";

export const stages: Stage[] = [
  { id: "prompt", name: "Prompt", short: "01", icon: Terminal, description: "The user supplies natural-language input.", beginnerExplanation: "You type a question or instruction in natural language.", technicalExplanation: "Input text is serialized into a model-serving request with applicable instructions and context." },
  { id: "context", name: "Context", short: "02", icon: CircleHelp, description: "Available conversation and instructions are considered as context.", beginnerExplanation: "The model receives relevant available context along with the current request.", technicalExplanation: "The effective input can include conversation history and other context supplied by the serving system." },
  { id: "tokens", name: "Tokenization", short: "03", icon: Zap, description: "Text is represented as tokens that the model can process.", beginnerExplanation: "A sentence becomes smaller pieces called tokens.", technicalExplanation: "A tokenizer maps text to discrete token IDs from a fixed vocabulary; boundaries are tokenizer-specific." },
  { id: "embeddings", name: "Embeddings", short: "04", icon: Cpu, description: "Tokens are mapped into high-dimensional numerical representations.", beginnerExplanation: "Each token is represented by numbers that capture learned patterns and relationships.", technicalExplanation: "Token IDs index learned embedding vectors, with positional information affecting computation." },
  { id: "attention", name: "Attention", short: "05", icon: BrainCircuit, description: "Attention lets each position weigh information from other positions.", beginnerExplanation: "The model weighs useful relationships between words and positions.", technicalExplanation: "Self-attention forms queries, keys, and values; scores determine how information mixes across positions." },
  { id: "transformer", name: "Transformer", short: "06", icon: Gauge, description: "Repeated transformer blocks transform the representations.", beginnerExplanation: "Transformation blocks repeatedly process the representations.", technicalExplanation: "Typical transformer blocks combine normalization, self-attention, residual paths, and a feed-forward network." },
  { id: "prediction", name: "Prediction", short: "07", icon: Sparkles, description: "The model produces scores for possible next tokens.", beginnerExplanation: "The model scores possible next tokens and a decoding method chooses one.", technicalExplanation: "The final representation is projected to vocabulary logits and a decoding procedure selects token behavior." },
  { id: "output", name: "Output", short: "08", icon: Terminal, description: "Selected tokens are repeatedly decoded to form a response.", beginnerExplanation: "The selected token is added to the context and the process repeats.", technicalExplanation: "Autoregressive decoding appends generated tokens and feeds the updated sequence back for the next step." }
];

export const stageIndex = (id: StageId) => stages.findIndex(stage => stage.id === id);